
services:

  db:
    image: postgres:latest
    container_name: postgrescontainer
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgresdb:/var/lib/postgresql
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  postgresdb: